name: ci

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
    tags: ["*"]


defaults:
  run:
    working-directory: terraform

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    # Initialize terraform with no remote state store and
    # validate resources.
    - run: terraform init -backend=false
    - run: terraform fmt -recursive -check
    - run: terraform validate
